"""Render a :class:`TestReportResponse` to a professional PDF (bytes)."""

from __future__ import annotations

import base64
import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image,
    ListFlowable,
    ListItem,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.modules.test_report.schemas import TestReportResponse

_ACCENT = colors.HexColor("#00BFFF")
_DARK = colors.HexColor("#040404")


def build_pdf(report: TestReportResponse) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        title=report.title,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
    )
    styles = _styles()
    story: list = []

    story.append(Paragraph("EngineerGPT — Test Report", styles["Brand"]))
    story.append(Paragraph(report.title, styles["Title2"]))
    story.append(
        Paragraph(
            f"Rows: {report.row_count} &nbsp;·&nbsp; Signals: {report.column_count} "
            f"&nbsp;·&nbsp; Generated by: {report.generated_by}",
            styles["Meta"],
        )
    )
    story.append(Spacer(1, 8 * mm))

    story.append(Paragraph("Executive Summary", styles["H2"]))
    story.append(Paragraph(report.executive_summary, styles["Body"]))
    story.append(Spacer(1, 6 * mm))

    if report.findings:
        story.append(Paragraph("Key Findings", styles["H2"]))
        story.append(
            _bullets(
                f"{f.statement} "
                f'<font color="#6b7280">(confidence {f.confidence:.0%}, {f.citation})</font>'
                for f in report.findings
            )
        )
        story.append(Spacer(1, 6 * mm))

    if report.anomalies:
        story.append(Paragraph("Anomaly Detection", styles["H2"]))
        table_data = [["Column", "Severity", "Description"]]
        table_data += [[a.column, a.severity.upper(), a.description] for a in report.anomalies]
        story.append(_anomaly_table(table_data))
        story.append(Spacer(1, 6 * mm))

    for chart in report.charts:
        story.append(Paragraph(chart.title, styles["H2"]))
        story.append(_image_from_b64(chart.image_base64))
        story.append(Spacer(1, 4 * mm))

    if report.conclusions:
        story.append(Paragraph("Conclusions", styles["H2"]))
        story.append(_bullets(report.conclusions))
        story.append(Spacer(1, 6 * mm))

    if report.recommendations:
        story.append(Paragraph("Recommendations", styles["H2"]))
        story.append(_bullets(report.recommendations))

    doc.build(story)
    return buffer.getvalue()


def _styles():
    base = getSampleStyleSheet()
    return {
        "Brand": ParagraphStyle(
            "Brand", parent=base["Normal"], fontSize=10, textColor=_ACCENT, spaceAfter=2
        ),
        "Title2": ParagraphStyle(
            "Title2", parent=base["Title"], fontSize=22, textColor=colors.HexColor("#111827")
        ),
        "Meta": ParagraphStyle(
            "Meta", parent=base["Normal"], fontSize=9, textColor=colors.HexColor("#6b7280")
        ),
        "H2": ParagraphStyle(
            "H2",
            parent=base["Heading2"],
            fontSize=13,
            textColor=colors.HexColor("#1f2937"),
            spaceBefore=4,
            spaceAfter=4,
        ),
        "Body": ParagraphStyle("Body", parent=base["Normal"], fontSize=10, leading=15),
    }


def _bullets(items) -> ListFlowable:
    style = ParagraphStyle("Bullet", fontSize=10, leading=15)
    return ListFlowable(
        [ListItem(Paragraph(str(i), style), leftIndent=6) for i in items],
        bulletType="bullet",
        bulletColor=_ACCENT,
    )


def _anomaly_table(data) -> Table:
    table = Table(data, colWidths=[35 * mm, 25 * mm, 110 * mm])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), _DARK),
                ("TEXTCOLOR", (0, 0), (-1, 0), _ACCENT),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#e5e7eb")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9fafb")]),
            ]
        )
    )
    return table


def _image_from_b64(b64: str) -> Image:
    raw = base64.b64decode(b64)
    img = Image(io.BytesIO(raw))
    max_w = 165 * mm
    if img.imageWidth > max_w:
        ratio = max_w / img.imageWidth
        img.drawWidth = max_w
        img.drawHeight = img.imageHeight * ratio
    return img
